import os
import json
import math
import string
import uuid
import sqlite3
from datetime import datetime

import nltk
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

nltk.download("punkt_tab", quiet=True)

load_dotenv()

# KNOWN LIMITATIONS
# -----------------
# 1. Short-text unreliability: stylometric signals (burstiness, TTR,
#    punctuation density) require ~50+ words and 5+ sentences to
#    stabilize. Texts below this threshold return 0.5 for Signal 2
#    and should be treated as LLM-signal-only classifications.
#
# 2. Adversarial evasion: stylometric signals are trivially defeated
#    by anyone aware of what the detector measures — adding one short
#    sentence, using a contraction, or breaking a long sentence shifts
#    CV immediately. This system is designed to catch unsophisticated
#    AI use (copy-paste slop, bulk content farms), not a determined
#    adversary who knows the detection approach.
#
# 3. LLM prompt evasion: the LLM signal asks "does this read like AI
#    output?" — which depends on the current distribution of AI writing.
#    Prompting the generator to write casually, vary sentence length,
#    or use imperfect grammar drifts output outside the distribution
#    the detector recognizes. Detector and evader share the same
#    underlying model capabilities.
#
# 4. ESL fairness risk: non-native English writers producing careful,
#    grammatically correct prose in a second language naturally exhibit
#    low burstiness and conservative vocabulary — the same surface
#    features this detector keys on. The 0.9 threshold is set high
#    deliberately to reduce false positives, but ESL writers remain
#    at elevated risk of landing in the LIKELY_AI band (0.4–0.9).
#    See: Liang et al., 2023 — GPT Detectors Are Biased Against
#    Non-Native English Writers (arxiv.org/abs/2304.02819)
#
# 5. Distribution shift: the LLM signal degrades as AI writing styles
#    evolve across model generations. What reads as AI today may not
#    match the patterns of future models.
#
# 6. Base rate problem: at low AI-content prevalence, even a high-
#    accuracy detector produces more false positives than true
#    positives. The 0.9 hard threshold reflects a design choice that
#    false positives (wrongly flagging a human) are more costly than
#    false negatives.

app = Flask(__name__)
DB_PATH = "audit.db"

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

SYSTEM_PROMPT = (
    "You are an AI content detector. Given a piece of text, assess whether it was written by a human "
    "or generated by AI. Return ONLY valid JSON in this format, with no explanation:\n"
    "{\n"
    '  "attribution": "human" | "likely_human" | "uncertain" | "likely_ai" | "ai",\n'
    '  "score": <float between 0.0 and 1.0 where 0.0 = definitely human, 1.0 = definitely AI>,\n'
    '  "reasoning": "<one sentence explanation>"\n'
    "}"
)


def init_db() -> None:
    con = sqlite3.connect(DB_PATH)
    con.execute("""
        CREATE TABLE IF NOT EXISTS log (
            id                INTEGER PRIMARY KEY AUTOINCREMENT,
            content_id        TEXT,
            creator_id        TEXT,
            timestamp         TEXT,
            attribution       TEXT,
            confidence        REAL,
            llm_score         REAL,
            stylometric_score REAL,
            label             TEXT,
            block             INTEGER,
            status            TEXT
        )
    """)
    # Migration guards — one per column added after initial schema.
    # ALTER TABLE does not support IF NOT EXISTS in SQLite, so we catch the error.
    for ddl in (
        "ALTER TABLE log ADD COLUMN signal_2_score REAL DEFAULT NULL",
        "ALTER TABLE log ADD COLUMN stylometric_score REAL DEFAULT NULL",
        "ALTER TABLE log ADD COLUMN label TEXT DEFAULT NULL",
        "ALTER TABLE log ADD COLUMN block INTEGER DEFAULT NULL",
        "ALTER TABLE log ADD COLUMN appeal_reasoning TEXT DEFAULT NULL",
        "ALTER TABLE log ADD COLUMN appeal_timestamp TEXT DEFAULT NULL",
    ):
        try:
            con.execute(ddl)
        except sqlite3.OperationalError:
            pass
    con.commit()
    con.close()


def write_log(entry: dict) -> None:
    con = sqlite3.connect(DB_PATH)
    con.execute(
        """
        INSERT INTO log
            (content_id, creator_id, timestamp, attribution, confidence,
             llm_score, stylometric_score, label, block, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            entry["content_id"],
            entry["creator_id"],
            entry["timestamp"],
            entry["attribution"],
            entry["confidence"],
            entry["llm_score"],
            entry["stylometric_score"],
            entry["label"],
            int(entry["block"]),
            entry["status"],
        ),
    )
    con.commit()
    con.close()


def fetch_log(limit: int) -> list[dict]:
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT * FROM log ORDER BY id DESC LIMIT ?", (limit,)
    ).fetchall()
    con.close()
    result = []
    for row in rows:
        entry = dict(row)
        if entry.get("block") is not None:
            entry["block"] = bool(entry["block"])
        result.append(entry)
    return result


def score_llm(text: str) -> dict:
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    try:
        response = client.chat.completions.create(
            model="llama3-8b-8192",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content.strip()
        return json.loads(raw)
    except Exception:
        return {"attribution": "uncertain", "score": 0.5, "reasoning": "parse error"}


def score_stylometric(text: str) -> float:
    sentences = nltk.sent_tokenize(text)
    words = [w.lower().strip(string.punctuation) for w in text.split() if w.strip(string.punctuation)]

    # Sub-metric A: sentence length variance (burstiness).
    # Weighted highest (0.5) — irregular sentence rhythm is the most reliable
    # surface signal separating human from AI writing.
    if len(sentences) >= 3:
        lengths = [len(s.split()) for s in sentences]
        mean = sum(lengths) / len(lengths)
        if mean > 0:
            std_dev = math.sqrt(sum((ln - mean) ** 2 for ln in lengths) / len(lengths))
            cv = std_dev / mean
            # High CV (irregular) → human-like → invert to low score.
            # Denominator is 1.0 (not 2.0) because real casual writing peaks around
            # cv~0.6; a ceiling of 2.0 compresses everything into the AI-like half.
            variance_score = 1.0 - min(cv, 1.0)
        else:
            variance_score = 0.5
    else:
        variance_score = 0.5

    # Sub-metric B: type-token ratio.
    # Secondary weight (0.3) — AI generates higher lexical diversity per token
    # through optimized sampling; humans repeat words more naturally.
    # Minimum 50 words: TTR always saturates near 1.0 on short texts regardless
    # of source, making it a useless discriminator below that threshold.
    if len(words) >= 50:
        ttr = len(set(words)) / len(words)
        ttr_score = min(ttr / 0.85, 1.0)
    else:
        ttr_score = 0.5

    # Sub-metric C: comma density.
    # Weak corroborating signal only (0.2) — AI reliably uses 1.5–2.5 commas
    # per sentence; outside that range is less diagnostic on its own.
    if len(sentences) >= 2:
        commas_per_sentence = text.count(",") / len(sentences)
        punct_score = 0.7 if 1.0 <= commas_per_sentence <= 3.0 else 0.3
    else:
        punct_score = 0.5

    stylometric_score = (0.5 * variance_score) + (0.3 * ttr_score) + (0.2 * punct_score)
    return round(max(0.0, min(1.0, stylometric_score)), 4)


def combine_scores(scores: list[float]) -> float:
    # LLM signal receives higher weight (0.6) because it reasons over semantics
    # and structure; stylometrics (0.4) captures surface patterns only.
    combined = (0.6 * scores[0]) + (0.4 * scores[1])
    return round(combined, 4)


def generate_label(score: float) -> dict:
    if score >= 0.9:
        return {"label": "AI_GENERATED", "block": True, "banner": None}
    if score >= 0.4:
        return {
            "label": "LIKELY_AI",
            "block": False,
            "banner": "This content may be AI-generated. Review before trusting.",
        }
    return {"label": "HUMAN", "block": False, "banner": None}


@app.route("/")
def home():
    return "Provenance Guard is running."


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON"}), 400

    text = body.get("text")
    creator_id = body.get("creator_id")

    if not text or not creator_id:
        return jsonify({"error": "Both 'text' and 'creator_id' are required"}), 400

    content_id = str(uuid.uuid4())
    llm_result = score_llm(text)
    stylometric_score = score_stylometric(text)
    confidence = combine_scores([llm_result["score"], stylometric_score])
    label_data = generate_label(confidence)

    write_log({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "attribution": llm_result["attribution"],
        "confidence": confidence,
        "llm_score": llm_result["score"],
        "stylometric_score": stylometric_score,
        "label": label_data["label"],
        "block": label_data["block"],
        "status": "classified",
    })

    return jsonify({
        "content_id": content_id,
        "attribution": llm_result["attribution"],
        "confidence": confidence,
        "label": label_data["label"],
        "block": label_data["block"],
        "banner": label_data["banner"],
        "signal_scores": {
            "llm": llm_result["score"],
            "stylometric": stylometric_score,
        },
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON"}), 400

    content_id = body.get("content_id")
    creator_reasoning = body.get("creator_reasoning", "").strip()

    if not content_id or not creator_reasoning:
        return jsonify({"error": "Both 'content_id' and 'creator_reasoning' are required"}), 400

    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    row = con.execute(
        "SELECT id FROM log WHERE content_id = ?", (content_id,)
    ).fetchone()

    if row is None:
        con.close()
        return jsonify({"error": f"content_id '{content_id}' not found"}), 404

    appeal_timestamp = datetime.utcnow().isoformat() + "Z"
    con.execute(
        """
        UPDATE log
           SET status = 'under_review',
               appeal_reasoning = ?,
               appeal_timestamp = ?
         WHERE content_id = ?
        """,
        (creator_reasoning, appeal_timestamp, content_id),
    )
    con.commit()
    con.close()

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Appeal received and is pending human review.",
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = fetch_log(limit=10)
    return jsonify({"entries": entries}), 200


init_db()

if __name__ == "__main__":
    app.run(port=5000, debug=True)
